import {
  KpiMetric,
  WeeklyVolumePoint,
  AlertItem,
  UserProfile,
  WarehouseHub,
} from './types';

/**
 * MOCK_DATA: Primary mock datasets for LogiSync Pro Dashboard Overview.
 * Designed for Indian MSME logistics context (inter-state corridors, GST/e-Way, cold-chain).
 */

export const MOCK_DATA_KPIS: KpiMetric[] = [
  {
    id: 'kpi-ontime',
    label: 'On-Time Delivery %',
    value: '94.8%',
    unit: '%',
    trendValue: '+2.4%',
    trendDirection: 'up',
    trendPeriod: 'vs last month',
    accent: 'success',
    isHero: true,
    subtext: 'Target SLA: 92.0% • 1,397 / 1,474 deliveries',
  },
  {
    id: 'kpi-savings',
    label: 'Cost Savings This Month',
    value: '₹1,84,500',
    unit: 'INR',
    trendValue: '+14.8%',
    trendDirection: 'up',
    trendPeriod: 'via Route AI',
    accent: 'brand',
    isHero: true,
    subtext: 'Saved 1,420 L diesel & toll route bypasses',
  },
  {
    id: 'kpi-fleet',
    label: 'Active Vehicles',
    value: '42',
    unit: 'of 48',
    trendValue: '+4',
    trendDirection: 'up',
    trendPeriod: 'on corridor today',
    accent: 'info',
    subtext: '6 vehicles in loading / scheduled service',
  },
  {
    id: 'kpi-delay-risk',
    label: 'Open Delay-Risk Shipments',
    value: '3',
    unit: 'Shipments',
    trendValue: '-2',
    trendDirection: 'down',
    trendPeriod: 'vs yesterday',
    accent: 'critical',
    subtext: 'Monitored on NH-48 & Western Freight Corridor',
  },
  {
    id: 'kpi-low-stock',
    label: 'Low-Stock SKUs',
    value: '7',
    unit: 'SKUs',
    trendValue: '+2',
    trendDirection: 'up',
    trendPeriod: 'needs reorder',
    accent: 'warning',
    subtext: 'Immediate reorder recommended at Bhiwandi',
  },
];

export const MOCK_DATA_WEEKLY_VOLUME: WeeklyVolumePoint[] = [
  {
    day: 'Mon',
    fullDay: 'Monday',
    volume: 184,
    onTimeDeliveries: 175,
    delayedDeliveries: 9,
    onTimeRate: 95.1,
  },
  {
    day: 'Tue',
    fullDay: 'Tuesday',
    volume: 215,
    onTimeDeliveries: 204,
    delayedDeliveries: 11,
    onTimeRate: 94.8,
  },
  {
    day: 'Wed',
    fullDay: 'Wednesday',
    volume: 242,
    onTimeDeliveries: 231,
    delayedDeliveries: 11,
    onTimeRate: 95.4,
  },
  {
    day: 'Thu',
    fullDay: 'Thursday',
    volume: 228,
    onTimeDeliveries: 216,
    delayedDeliveries: 12,
    onTimeRate: 94.7,
  },
  {
    day: 'Fri',
    fullDay: 'Friday',
    volume: 295,
    onTimeDeliveries: 279,
    delayedDeliveries: 16,
    onTimeRate: 94.5,
  },
  {
    day: 'Sat',
    fullDay: 'Saturday',
    volume: 198,
    onTimeDeliveries: 189,
    delayedDeliveries: 9,
    onTimeRate: 95.4,
  },
  {
    day: 'Sun',
    fullDay: 'Sunday',
    volume: 112,
    onTimeDeliveries: 108,
    delayedDeliveries: 4,
    onTimeRate: 96.4,
  },
];

export const MOCK_DATA_ALERTS: AlertItem[] = [
  {
    id: 'alt-01',
    severity: 'critical',
    title: 'Delay Risk: NH-48 Heavy Congestion',
    message: 'Vehicle MH-12-Q-4491 delayed by ~45 mins near Khed-Shivapur Toll. AI suggested alternate SH-119 detour.',
    entityTag: 'MH-12-Q-4491',
    timestamp: '2026-09-08T20:55:00Z',
    relativeTime: '12m ago',
    isRead: false,
    actionUrl: '/live-map',
  },
  {
    id: 'alt-02',
    severity: 'critical',
    title: 'Cold-Chain SLA Breach Warning',
    message: 'Reefer Truck DL-01-AX-9920 cargo sensor logged 7.8°C (threshold max 4.0°C). Driver notified via SMS.',
    entityTag: 'DL-01-AX-9920',
    timestamp: '2026-09-08T20:38:00Z',
    relativeTime: '29m ago',
    isRead: false,
    actionUrl: '/fleet',
  },
  {
    id: 'alt-03',
    severity: 'warning',
    title: 'Low Inventory Threshold at Hub',
    message: 'SKU #IND-5521 (5-Ply Corrugated Shipping Box) below reorder level (140 units left).',
    entityTag: 'SKU #IND-5521',
    timestamp: '2026-09-08T20:20:00Z',
    relativeTime: '47m ago',
    isRead: false,
    actionUrl: '/warehouse',
  },
  {
    id: 'alt-04',
    severity: 'warning',
    title: 'Prolonged Vehicle Idle',
    message: 'Vehicle KA-04-E-1029 idle >115 mins with ignition ON at Peenya Logistics Gate 3.',
    entityTag: 'KA-04-E-1029',
    timestamp: '2026-09-08T19:55:00Z',
    relativeTime: '1h 12m ago',
    isRead: true,
    actionUrl: '/driver-analytics',
  },
  {
    id: 'alt-05',
    severity: 'info',
    title: 'Blockchain e-Way Bill Verified',
    message: 'Consignment CN-98204-MH e-Way Bill #88392019482 cryptographically verified on ledger.',
    entityTag: 'CN-98204',
    timestamp: '2026-09-08T18:45:00Z',
    relativeTime: '2h 22m ago',
    isRead: true,
    actionUrl: '/blockchain',
  },
];

export const MOCK_DATA_USER: UserProfile = {
  name: 'Rajesh Sharma',
  role: 'Admin',
  email: 'r.sharma@ganeshlogistics.in',
  avatarInitials: 'RS',
  companyName: 'Shree Ganesh Logistics & Freight',
  currentHub: 'Bhiwandi Central Hub (MH)',
};

export const MOCK_DATA_HUBS: WarehouseHub[] = [
  {
    id: 'hub-01',
    name: 'Bhiwandi Central Hub',
    city: 'Thane / Mumbai',
    state: 'Maharashtra',
    code: 'BHW-01',
    activeVehicles: 24,
  },
  {
    id: 'hub-02',
    name: 'Okhla Industrial DC',
    city: 'New Delhi',
    state: 'Delhi NCR',
    code: 'OKH-02',
    activeVehicles: 10,
  },
  {
    id: 'hub-03',
    name: 'Peenya Logistics Park',
    city: 'Bengaluru',
    state: 'Karnataka',
    code: 'PNY-03',
    activeVehicles: 8,
  },
  {
    id: 'hub-04',
    name: 'Sriperumbudur Hub',
    city: 'Chennai',
    state: 'Tamil Nadu',
    code: 'SRP-04',
    activeVehicles: 6,
  },
];
